GET {{ URL }}/sys/admin
Content-Type: application/json

###
POST {{URL}}/category/page/1/10
Content-Type: application/json

{
    "name": "手机"
}

###
GET {{URL}}/category/list/tree


###
GET localhost:88/api/generator/category/list/tree


###测试认证请求
POST {{ URL }}/authentication
Content-Type: application/json

{
  "username": "root",
  "password": "admin"
}

###
GET {{ URL }}/queryCommentByArticle?articleId=4
Content-Type: application/x-www-form-urlencoded


### 获取用户角色信息
GET {{ URL }}/getUserOfRoleInfoBy?uid=1
Content-Type: application/x-www-form-urlencoded
jwtHead: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNjA5NDIwMzcwfQ.IerK502o3zEoWsn4xdupkmGB-IRE3oG3kEfNMFbtN0UeP8yJbQgyMjcaUcBYGwGmGZMtiP9R-Rv1vQWx44jheg

### 获取所有角色信息
GET {{ URL }}/getAllRole
Content-Type: application/x-www-form-urlencoded
###jwtHead: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb290IiwiZXhwIjoxNjA5NDIwMzcwfQ.IerK502o3zEoWsn4xdupkmGB-IRE3oG3kEfNMFbtN0UeP8yJbQgyMjcaUcBYGwGmGZMtiP9R-Rv1vQWx44jheg


###
POST {{ URL }}/addRole
Content-Type: application/json

{
    "ids":[1,2,3,4]
}


### 新增文章分类
POST {{ URL }}/add/articleChannel
Content-Type: application/json

{
  "type": "其他",
  "no": 99
}

### 查询所有的文章分类
GET {{ URL }}/getAll/articleChannel
Content-Type: application/json

{
  "type": "动漫",
  "no": 1
}

### 查询所有的角色
GET {{ URL }}/queryAllRole
Content-Type: application/json

###
GET {{ URL }}/getAllAdminNotifies
Content-Type: application/json

### OCR 发票信息识别

