#------------------- 数据源 -------------------#
generator.username=root
generator.password=admin
generator.url=jdbc:mysql://localhost:3306/cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
generator.driver-class-name=com.mysql.cj.jdbc.Driver
# 父包名
generator.package.parent=com.ww.mall.generator
# 需要生成的表名，多张表用英文逗号隔开 #
generator.table.name=user
# 表名前缀
generator.prefix=pms_