server:
  port: 88

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #服务注册地址
    gateway:
      routes:
        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}   # /api/foo  =>  /foo

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*), $\{segment}   # /api/foo  =>  /foo