# 开启优雅停机，默认值：immediate 为立即关闭
server:
  shutdown: graceful
spring:
  # hippo4j动态线程池
  dynamic:
    thread-pool:
      # 是否开启动态线程池
      enable: true
      # 是否打印 banner
      banner: true
      # 检查线程池状态，是否达到报警条件，单位毫秒
      check-state-interval: 3000
      # Nacos
      nacos:
        data-id: mall-dynamic-threadPool.yml
        group: DEFAULT
      # 配置中心文件格式
      config-file-type: yml
      # 动态线程池列表
      executors:
        - thread-pool-id: 'defaultThreadPoolExecutor'
          # 核心线程数
          core-pool-size: 20
          # 最大线程数
          maximum-pool-size: 20
          # 阻塞队列名称，参考 BlockingQueueTypeEnum，支持 SPI
          blocking-queue: 'LinkedBlockingQueue'
          # 阻塞队列大小
          queue-capacity: 10000
          # 执行超时时间，超过此时间发起报警，单位毫秒
          execute-time-out: 3000
          # 拒绝策略名称，参考 RejectedPolicyTypeEnum，支持 SPI
          rejected-handler: 'AbortPolicy'
          # 线程存活时间，单位秒
          keep-alive-time: 1024
          # 是否允许核心线程超时
          allow-core-thread-time-out: true
          # 线程工厂名称前缀
          thread-name-prefix: 'ww-mall-default'
          # 是否报警
          alarm: false
          # 活跃度报警阈值；假设线程池最大线程数 10，当线程数达到 8 发起报警
          active-alarm: 80
          # 容量报警阈值；假设阻塞队列容量 100，当容量达到 80 发起报警
          capacity-alarm: 80
          # 通知配置，线程池中通知配置如果存在，则会覆盖全局通知配置
#          notify:
            # 报警间隔，同一线程池下同一报警纬度，在 interval 时间内只会报警一次，单位分钟
#            interval: 8
            # 企业微信填写用户 ID（填写其它将无法达到 @ 效果）、钉钉填手机号、飞书填 ou_ 开头唯一 ID
#            receives: xxx

  main:
    # 开启循环依赖
    allow-circular-references: true
  lifecycle:
    # 设置缓冲期，最大等待时间，默认：30秒
    timeout-per-shutdown-phase: 60s
  servlet:
    multipart:
      # 配置单个文件大小限制
      max-file-size: 50MB
      # 配置单次请求文件大小限制
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        # 配置所有服务的元数据信息
        metadata:
          version: 1.0
          nacos.weight: 1
          # 心跳间隔。时间单位:毫秒。心跳间隔
          preserved.heart.beat.interval: 1000
          # 心跳暂停。时间单位:毫秒。 即服务端6秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.heart.beat.timeout: 3000
          # Ip删除超时。时间单位:毫秒。即服务端9秒收不到客户端心跳，会将该客户端注册的实例删除：
          preserved.ip.delete.timeout: 3000
  jackson:
    # 全局日期格式处理jackson时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    # 表单接收date
    format:
      date: yyyy-MM-dd HH:mm:ss

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

feign:
  # 开启sentinel feign支持【调用方（调用服务方）的熔断保护、被调用方（服务提供方）的降级保护】
  sentinel:
    enabled: true
  # feign超时配置
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

# minio
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: EZpgdNV3xJ0SLu3PqrAS
  secretKey: GH27GRD6c2Zfg4vmZPKE8FFZBuhNB7xMFPOCHu4Y

  # 流控规则持久化
#  cloud:
#    sentinel:
#      datasource:
#        flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: flow
#        degrade-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-degrade-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: degrade
#        param-flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-param-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: param-flow
#        system-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-system-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: system
#        authority-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-authority-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: authority
#        gw-flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-gw-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: gw-flow
#        gw-api-group-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-gw-api-group-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: gw-api-group
