spring:
  servlet:
    multipart:
      # 配置单个文件大小限制
      max-file-size: 10MB
      # 配置单次请求文件大小限制
      max-request-size: 20MB
  boot:
    admin:
      client:
        # 配置服务监控
        url: http://localhost:9999
  cloud:
    nacos:
      discovery:
        # 配置所有服务的元数据信息
        metadata:
          version: 1.0
          nacos.weight: 1
  jackson:
    # 全局日期格式处理jackson时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    # 表单接收date
    format:
      date: yyyy-MM-dd HH:mm:ss

management:
  endpoints:
    web:
      exposure:
        include: "*"
# feign超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

# minio
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: EZpgdNV3xJ0SLu3PqrAS
  secretKey: GH27GRD6c2Zfg4vmZPKE8FFZBuhNB7xMFPOCHu4Y

  # 流控规则持久化
#  cloud:
#    sentinel:
#      datasource:
#        flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: flow
#        degrade-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-degrade-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: degrade
#        param-flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-param-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: param-flow
#        system-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-system-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: system
#        authority-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-authority-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: authority
#        gw-flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-gw-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: gw-flow
#        gw-api-group-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-gw-api-group-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: gw-api-group
