// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/imRouter.proto

// Protobuf Java Version: 3.25.1
package com.ww.mall.proto.im.router;

public final class ImRouterProto {
  private ImRouterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021im/imRouter.proto\032\013im/im.proto\032\033google" +
      "/protobuf/empty.proto2\210\001\n\017ImRouterServic" +
      "e\0225\n\010routeMsg\022\021.ImMsgBodyRequest\032\026.googl" +
      "e.protobuf.Empty\022>\n\rbatchRouteMsg\022\025.ImMs" +
      "gBodyListRequest\032\026.google.protobuf.Empty" +
      "B.\n\033com.ww.mall.proto.im.routerB\rImRoute" +
      "rProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ww.mall.proto.im.ImProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    com.ww.mall.proto.im.ImProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
