// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/im.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.im;

public interface ImCommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImCommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
