// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/im.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.im;

public interface ImMsgBodyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMsgBodyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string seqId = 1;</code>
   * @return The seqId.
   */
  java.lang.String getSeqId();
  /**
   * <code>string seqId = 1;</code>
   * @return The bytes for seqId.
   */
  com.google.protobuf.ByteString
      getSeqIdBytes();

  /**
   * <code>int32 appId = 2;</code>
   * @return The appId.
   */
  int getAppId();

  /**
   * <code>int64 userId = 3;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>int32 bizCode = 5;</code>
   * @return The bizCode.
   */
  int getBizCode();

  /**
   * <code>string bizMsg = 6;</code>
   * @return The bizMsg.
   */
  java.lang.String getBizMsg();
  /**
   * <code>string bizMsg = 6;</code>
   * @return The bytes for bizMsg.
   */
  com.google.protobuf.ByteString
      getBizMsgBytes();
}
