// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/im.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.im;

/**
 * Protobuf type {@code ImMsgBodyRequest}
 */
public final class ImMsgBodyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImMsgBodyRequest)
    ImMsgBodyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImMsgBodyRequest.newBuilder() to construct.
  private ImMsgBodyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImMsgBodyRequest() {
    seqId_ = "";
    token_ = "";
    bizMsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImMsgBodyRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ww.app.proto.im.ImProto.internal_static_ImMsgBodyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ww.app.proto.im.ImProto.internal_static_ImMsgBodyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ww.app.proto.im.ImMsgBodyRequest.class, com.ww.app.proto.im.ImMsgBodyRequest.Builder.class);
  }

  public static final int SEQID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object seqId_ = "";
  /**
   * <code>string seqId = 1;</code>
   * @return The seqId.
   */
  @java.lang.Override
  public java.lang.String getSeqId() {
    java.lang.Object ref = seqId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      seqId_ = s;
      return s;
    }
  }
  /**
   * <code>string seqId = 1;</code>
   * @return The bytes for seqId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSeqIdBytes() {
    java.lang.Object ref = seqId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      seqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPID_FIELD_NUMBER = 2;
  private int appId_ = 0;
  /**
   * <code>int32 appId = 2;</code>
   * @return The appId.
   */
  @java.lang.Override
  public int getAppId() {
    return appId_;
  }

  public static final int USERID_FIELD_NUMBER = 3;
  private long userId_ = 0L;
  /**
   * <code>int64 userId = 3;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int TOKEN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object token_ = "";
  /**
   * <code>string token = 4;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <code>string token = 4;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIZCODE_FIELD_NUMBER = 5;
  private int bizCode_ = 0;
  /**
   * <code>int32 bizCode = 5;</code>
   * @return The bizCode.
   */
  @java.lang.Override
  public int getBizCode() {
    return bizCode_;
  }

  public static final int BIZMSG_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bizMsg_ = "";
  /**
   * <code>string bizMsg = 6;</code>
   * @return The bizMsg.
   */
  @java.lang.Override
  public java.lang.String getBizMsg() {
    java.lang.Object ref = bizMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bizMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string bizMsg = 6;</code>
   * @return The bytes for bizMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBizMsgBytes() {
    java.lang.Object ref = bizMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bizMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(seqId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, seqId_);
    }
    if (appId_ != 0) {
      output.writeInt32(2, appId_);
    }
    if (userId_ != 0L) {
      output.writeInt64(3, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, token_);
    }
    if (bizCode_ != 0) {
      output.writeInt32(5, bizCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bizMsg_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bizMsg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(seqId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, seqId_);
    }
    if (appId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, appId_);
    }
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, token_);
    }
    if (bizCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, bizCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bizMsg_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bizMsg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ww.app.proto.im.ImMsgBodyRequest)) {
      return super.equals(obj);
    }
    com.ww.app.proto.im.ImMsgBodyRequest other = (com.ww.app.proto.im.ImMsgBodyRequest) obj;

    if (!getSeqId()
        .equals(other.getSeqId())) return false;
    if (getAppId()
        != other.getAppId()) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (getBizCode()
        != other.getBizCode()) return false;
    if (!getBizMsg()
        .equals(other.getBizMsg())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEQID_FIELD_NUMBER;
    hash = (53 * hash) + getSeqId().hashCode();
    hash = (37 * hash) + APPID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + BIZCODE_FIELD_NUMBER;
    hash = (53 * hash) + getBizCode();
    hash = (37 * hash) + BIZMSG_FIELD_NUMBER;
    hash = (53 * hash) + getBizMsg().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ww.app.proto.im.ImMsgBodyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ww.app.proto.im.ImMsgBodyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ww.app.proto.im.ImMsgBodyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ww.app.proto.im.ImMsgBodyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ImMsgBodyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImMsgBodyRequest)
      com.ww.app.proto.im.ImMsgBodyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ww.app.proto.im.ImProto.internal_static_ImMsgBodyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ww.app.proto.im.ImProto.internal_static_ImMsgBodyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ww.app.proto.im.ImMsgBodyRequest.class, com.ww.app.proto.im.ImMsgBodyRequest.Builder.class);
    }

    // Construct using com.ww.mall.proto.im.ImMsgBodyRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      seqId_ = "";
      appId_ = 0;
      userId_ = 0L;
      token_ = "";
      bizCode_ = 0;
      bizMsg_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ww.app.proto.im.ImProto.internal_static_ImMsgBodyRequest_descriptor;
    }

    @java.lang.Override
    public com.ww.app.proto.im.ImMsgBodyRequest getDefaultInstanceForType() {
      return com.ww.app.proto.im.ImMsgBodyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ww.app.proto.im.ImMsgBodyRequest build() {
      com.ww.app.proto.im.ImMsgBodyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ww.app.proto.im.ImMsgBodyRequest buildPartial() {
      com.ww.app.proto.im.ImMsgBodyRequest result = new com.ww.app.proto.im.ImMsgBodyRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.ww.app.proto.im.ImMsgBodyRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.seqId_ = seqId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.appId_ = appId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.token_ = token_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bizCode_ = bizCode_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.bizMsg_ = bizMsg_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ww.app.proto.im.ImMsgBodyRequest) {
        return mergeFrom((com.ww.app.proto.im.ImMsgBodyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ww.app.proto.im.ImMsgBodyRequest other) {
      if (other == com.ww.app.proto.im.ImMsgBodyRequest.getDefaultInstance()) return this;
      if (!other.getSeqId().isEmpty()) {
        seqId_ = other.seqId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAppId() != 0) {
        setAppId(other.getAppId());
      }
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getBizCode() != 0) {
        setBizCode(other.getBizCode());
      }
      if (!other.getBizMsg().isEmpty()) {
        bizMsg_ = other.bizMsg_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              seqId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              appId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              token_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              bizCode_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              bizMsg_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object seqId_ = "";
    /**
     * <code>string seqId = 1;</code>
     * @return The seqId.
     */
    public java.lang.String getSeqId() {
      java.lang.Object ref = seqId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seqId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string seqId = 1;</code>
     * @return The bytes for seqId.
     */
    public com.google.protobuf.ByteString
        getSeqIdBytes() {
      java.lang.Object ref = seqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string seqId = 1;</code>
     * @param value The seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      seqId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string seqId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqId() {
      seqId_ = getDefaultInstance().getSeqId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string seqId = 1;</code>
     * @param value The bytes for seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      seqId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int appId_ ;
    /**
     * <code>int32 appId = 2;</code>
     * @return The appId.
     */
    @java.lang.Override
    public int getAppId() {
      return appId_;
    }
    /**
     * <code>int32 appId = 2;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(int value) {

      appId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 appId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      appId_ = 0;
      onChanged();
      return this;
    }

    private long userId_ ;
    /**
     * <code>int64 userId = 3;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 3;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <code>string token = 4;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string token = 4;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string token = 4;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      token_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string token = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      token_ = getDefaultInstance().getToken();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string token = 4;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      token_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int bizCode_ ;
    /**
     * <code>int32 bizCode = 5;</code>
     * @return The bizCode.
     */
    @java.lang.Override
    public int getBizCode() {
      return bizCode_;
    }
    /**
     * <code>int32 bizCode = 5;</code>
     * @param value The bizCode to set.
     * @return This builder for chaining.
     */
    public Builder setBizCode(int value) {

      bizCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bizCode = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBizCode() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bizCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bizMsg_ = "";
    /**
     * <code>string bizMsg = 6;</code>
     * @return The bizMsg.
     */
    public java.lang.String getBizMsg() {
      java.lang.Object ref = bizMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bizMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bizMsg = 6;</code>
     * @return The bytes for bizMsg.
     */
    public com.google.protobuf.ByteString
        getBizMsgBytes() {
      java.lang.Object ref = bizMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bizMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bizMsg = 6;</code>
     * @param value The bizMsg to set.
     * @return This builder for chaining.
     */
    public Builder setBizMsg(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bizMsg_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string bizMsg = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBizMsg() {
      bizMsg_ = getDefaultInstance().getBizMsg();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string bizMsg = 6;</code>
     * @param value The bytes for bizMsg to set.
     * @return This builder for chaining.
     */
    public Builder setBizMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bizMsg_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImMsgBodyRequest)
  }

  // @@protoc_insertion_point(class_scope:ImMsgBodyRequest)
  private static final com.ww.app.proto.im.ImMsgBodyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ww.app.proto.im.ImMsgBodyRequest();
  }

  public static com.ww.app.proto.im.ImMsgBodyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImMsgBodyRequest>
      PARSER = new com.google.protobuf.AbstractParser<ImMsgBodyRequest>() {
    @java.lang.Override
    public ImMsgBodyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ImMsgBodyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImMsgBodyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ww.app.proto.im.ImMsgBodyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

