// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/im.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.im;

public final class ImProto {
  private ImProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMsgBodyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMsgBodyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImMsgBodyListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImMsgBodyListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImCommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImCommonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013im/im.proto\"p\n\020ImMsgBodyRequest\022\r\n\005seq" +
      "Id\030\001 \001(\t\022\r\n\005appId\030\002 \001(\005\022\016\n\006userId\030\003 \001(\003\022" +
      "\r\n\005token\030\004 \001(\t\022\017\n\007bizCode\030\005 \001(\005\022\016\n\006bizMs" +
      "g\030\006 \001(\t\"@\n\024ImMsgBodyListRequest\022(\n\rimMsg" +
      "BodyList\030\001 \003(\0132\021.ImMsgBodyRequest\"#\n\020ImC" +
      "ommonResponse\022\017\n\007success\030\001 \001(\010B \n\023com.ww" +
      ".app.proto.imB\007ImProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImMsgBodyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImMsgBodyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMsgBodyRequest_descriptor,
        new java.lang.String[] { "SeqId", "AppId", "UserId", "Token", "BizCode", "BizMsg", });
    internal_static_ImMsgBodyListRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ImMsgBodyListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImMsgBodyListRequest_descriptor,
        new java.lang.String[] { "ImMsgBodyList", });
    internal_static_ImCommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ImCommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImCommonResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
