// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/imMsgBiz.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.im.biz;

public final class ImMsgBizProto {
  private ImMsgBizProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021im/imMsgBiz.proto\032\013im/im.proto\032\033google" +
      "/protobuf/empty.proto2K\n\017ImMsgBizService" +
      "\0228\n\013handleImMsg\022\021.ImMsgBodyRequest\032\026.goo" +
      "gle.protobuf.EmptyB*\n\027com.ww.app.proto.i" +
      "m.bizB\rImMsgBizProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ww.app.proto.im.ImProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    com.ww.app.proto.im.ImProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
