# 开启优雅停机，默认值：immediate 为立即关闭
server:
  shutdown: graceful
spring:
  main:
    # 开启循环依赖
    allow-circular-references: true
  lifecycle:
    # 设置缓冲期，最大等待时间，默认：30秒
    timeout-per-shutdown-phase: 60s
  servlet:
    multipart:
      # 配置单个文件大小限制
      max-file-size: 50MB
      # 配置单次请求文件大小限制
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        # 配置所有服务的元数据信息
        metadata:
          version: 1.0
          nacos.weight: 1
          # 心跳间隔。时间单位:毫秒。心跳间隔
          preserved.heart.beat.interval: 1000
          # 心跳暂停。时间单位:毫秒。 即服务端6秒收不到客户端心跳，会将该客户端注册的实例设为不健康：
          preserved.heart.beat.timeout: 3000
          # Ip删除超时。时间单位:毫秒。即服务端9秒收不到客户端心跳，会将该客户端注册的实例删除：
          preserved.ip.delete.timeout: 3000
  jackson:
    # 全局日期格式处理jackson时间格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    # 表单接收date
    format:
      date: yyyy-MM-dd HH:mm:ss

feign:
  # 开启sentinel feign支持【调用方（调用服务方）的熔断保护、被调用方（服务提供方）的降级保护】
  sentinel:
    enabled: true
  # feign超时配置
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000

# minio
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: EZpgdNV3xJ0SLu3PqrAS
  secretKey: GH27GRD6c2Zfg4vmZPKE8FFZBuhNB7xMFPOCHu4Y

  # 流控规则持久化
#  cloud:
#    sentinel:
#      datasource:
#        flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: flow
#        degrade-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-degrade-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: degrade
#        param-flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-param-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: param-flow
#        system-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-system-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: system
#        authority-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-authority-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: authority
#        gw-flow-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-gw-flow-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: gw-flow
#        gw-api-group-rules:
#          nacos:
#            server-addr: ${spring.cloud.nacos.discovery.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            data-id: ${spring.application.name}-${spring.profiles.active}-gw-api-group-rule.json
#            group-id: SENTINEL_RULE
#            data-type: json
#            rule-type: gw-api-group
