// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Future.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.hello;

public interface FutureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FutureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
