// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Future.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.hello;

public final class FutureProto {
  private FutureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FutureRequest_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FutureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FutureResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FutureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Future.proto\"\035\n\rFutureRequest\022\014\n\004name\030" +
      "\001 \001(\t\" \n\016FutureResponse\022\016\n\006result\030\001 \001(\t2" +
      ":\n\rFutureService\022)\n\004test\022\016.FutureRequest" +
      "\032\017.FutureResponse\"\000B(\n\027com.ww.mall.proto" +
      ".helloB\013FutureProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FutureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FutureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FutureRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_FutureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FutureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FutureResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
