// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/im.proto

// Protobuf Java Version: 3.25.1
package com.ww.mall.proto.im;

public interface ImMsgBodyListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ImMsgBodyListRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  java.util.List<com.ww.mall.proto.im.ImMsgBodyRequest> 
      getImMsgBodyListList();
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  com.ww.mall.proto.im.ImMsgBodyRequest getImMsgBodyList(int index);
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  int getImMsgBodyListCount();
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  java.util.List<? extends com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder> 
      getImMsgBodyListOrBuilderList();
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder getImMsgBodyListOrBuilder(
      int index);
}
