// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/im.proto

// Protobuf Java Version: 3.25.1
package com.ww.mall.proto.im;

/**
 * Protobuf type {@code ImMsgBodyListRequest}
 */
public final class ImMsgBodyListRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ImMsgBodyListRequest)
    ImMsgBodyListRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ImMsgBodyListRequest.newBuilder() to construct.
  private ImMsgBodyListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ImMsgBodyListRequest() {
    imMsgBodyList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ImMsgBodyListRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ww.mall.proto.im.ImProto.internal_static_ImMsgBodyListRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ww.mall.proto.im.ImProto.internal_static_ImMsgBodyListRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ww.mall.proto.im.ImMsgBodyListRequest.class, com.ww.mall.proto.im.ImMsgBodyListRequest.Builder.class);
  }

  public static final int IMMSGBODYLIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.ww.mall.proto.im.ImMsgBodyRequest> imMsgBodyList_;
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.ww.mall.proto.im.ImMsgBodyRequest> getImMsgBodyListList() {
    return imMsgBodyList_;
  }
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder> 
      getImMsgBodyListOrBuilderList() {
    return imMsgBodyList_;
  }
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  @java.lang.Override
  public int getImMsgBodyListCount() {
    return imMsgBodyList_.size();
  }
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  @java.lang.Override
  public com.ww.mall.proto.im.ImMsgBodyRequest getImMsgBodyList(int index) {
    return imMsgBodyList_.get(index);
  }
  /**
   * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
   */
  @java.lang.Override
  public com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder getImMsgBodyListOrBuilder(
      int index) {
    return imMsgBodyList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < imMsgBodyList_.size(); i++) {
      output.writeMessage(1, imMsgBodyList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < imMsgBodyList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, imMsgBodyList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ww.mall.proto.im.ImMsgBodyListRequest)) {
      return super.equals(obj);
    }
    com.ww.mall.proto.im.ImMsgBodyListRequest other = (com.ww.mall.proto.im.ImMsgBodyListRequest) obj;

    if (!getImMsgBodyListList()
        .equals(other.getImMsgBodyListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getImMsgBodyListCount() > 0) {
      hash = (37 * hash) + IMMSGBODYLIST_FIELD_NUMBER;
      hash = (53 * hash) + getImMsgBodyListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ww.mall.proto.im.ImMsgBodyListRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ww.mall.proto.im.ImMsgBodyListRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ImMsgBodyListRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ImMsgBodyListRequest)
      com.ww.mall.proto.im.ImMsgBodyListRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ww.mall.proto.im.ImProto.internal_static_ImMsgBodyListRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ww.mall.proto.im.ImProto.internal_static_ImMsgBodyListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ww.mall.proto.im.ImMsgBodyListRequest.class, com.ww.mall.proto.im.ImMsgBodyListRequest.Builder.class);
    }

    // Construct using com.ww.mall.proto.im.ImMsgBodyListRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (imMsgBodyListBuilder_ == null) {
        imMsgBodyList_ = java.util.Collections.emptyList();
      } else {
        imMsgBodyList_ = null;
        imMsgBodyListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ww.mall.proto.im.ImProto.internal_static_ImMsgBodyListRequest_descriptor;
    }

    @java.lang.Override
    public com.ww.mall.proto.im.ImMsgBodyListRequest getDefaultInstanceForType() {
      return com.ww.mall.proto.im.ImMsgBodyListRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.ww.mall.proto.im.ImMsgBodyListRequest build() {
      com.ww.mall.proto.im.ImMsgBodyListRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ww.mall.proto.im.ImMsgBodyListRequest buildPartial() {
      com.ww.mall.proto.im.ImMsgBodyListRequest result = new com.ww.mall.proto.im.ImMsgBodyListRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.ww.mall.proto.im.ImMsgBodyListRequest result) {
      if (imMsgBodyListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          imMsgBodyList_ = java.util.Collections.unmodifiableList(imMsgBodyList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.imMsgBodyList_ = imMsgBodyList_;
      } else {
        result.imMsgBodyList_ = imMsgBodyListBuilder_.build();
      }
    }

    private void buildPartial0(com.ww.mall.proto.im.ImMsgBodyListRequest result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ww.mall.proto.im.ImMsgBodyListRequest) {
        return mergeFrom((com.ww.mall.proto.im.ImMsgBodyListRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ww.mall.proto.im.ImMsgBodyListRequest other) {
      if (other == com.ww.mall.proto.im.ImMsgBodyListRequest.getDefaultInstance()) return this;
      if (imMsgBodyListBuilder_ == null) {
        if (!other.imMsgBodyList_.isEmpty()) {
          if (imMsgBodyList_.isEmpty()) {
            imMsgBodyList_ = other.imMsgBodyList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureImMsgBodyListIsMutable();
            imMsgBodyList_.addAll(other.imMsgBodyList_);
          }
          onChanged();
        }
      } else {
        if (!other.imMsgBodyList_.isEmpty()) {
          if (imMsgBodyListBuilder_.isEmpty()) {
            imMsgBodyListBuilder_.dispose();
            imMsgBodyListBuilder_ = null;
            imMsgBodyList_ = other.imMsgBodyList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            imMsgBodyListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getImMsgBodyListFieldBuilder() : null;
          } else {
            imMsgBodyListBuilder_.addAllMessages(other.imMsgBodyList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ww.mall.proto.im.ImMsgBodyRequest m =
                  input.readMessage(
                      com.ww.mall.proto.im.ImMsgBodyRequest.parser(),
                      extensionRegistry);
              if (imMsgBodyListBuilder_ == null) {
                ensureImMsgBodyListIsMutable();
                imMsgBodyList_.add(m);
              } else {
                imMsgBodyListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ww.mall.proto.im.ImMsgBodyRequest> imMsgBodyList_ =
      java.util.Collections.emptyList();
    private void ensureImMsgBodyListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        imMsgBodyList_ = new java.util.ArrayList<com.ww.mall.proto.im.ImMsgBodyRequest>(imMsgBodyList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ww.mall.proto.im.ImMsgBodyRequest, com.ww.mall.proto.im.ImMsgBodyRequest.Builder, com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder> imMsgBodyListBuilder_;

    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public java.util.List<com.ww.mall.proto.im.ImMsgBodyRequest> getImMsgBodyListList() {
      if (imMsgBodyListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(imMsgBodyList_);
      } else {
        return imMsgBodyListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public int getImMsgBodyListCount() {
      if (imMsgBodyListBuilder_ == null) {
        return imMsgBodyList_.size();
      } else {
        return imMsgBodyListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public com.ww.mall.proto.im.ImMsgBodyRequest getImMsgBodyList(int index) {
      if (imMsgBodyListBuilder_ == null) {
        return imMsgBodyList_.get(index);
      } else {
        return imMsgBodyListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder setImMsgBodyList(
        int index, com.ww.mall.proto.im.ImMsgBodyRequest value) {
      if (imMsgBodyListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.set(index, value);
        onChanged();
      } else {
        imMsgBodyListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder setImMsgBodyList(
        int index, com.ww.mall.proto.im.ImMsgBodyRequest.Builder builderForValue) {
      if (imMsgBodyListBuilder_ == null) {
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.set(index, builderForValue.build());
        onChanged();
      } else {
        imMsgBodyListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder addImMsgBodyList(com.ww.mall.proto.im.ImMsgBodyRequest value) {
      if (imMsgBodyListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.add(value);
        onChanged();
      } else {
        imMsgBodyListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder addImMsgBodyList(
        int index, com.ww.mall.proto.im.ImMsgBodyRequest value) {
      if (imMsgBodyListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.add(index, value);
        onChanged();
      } else {
        imMsgBodyListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder addImMsgBodyList(
        com.ww.mall.proto.im.ImMsgBodyRequest.Builder builderForValue) {
      if (imMsgBodyListBuilder_ == null) {
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.add(builderForValue.build());
        onChanged();
      } else {
        imMsgBodyListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder addImMsgBodyList(
        int index, com.ww.mall.proto.im.ImMsgBodyRequest.Builder builderForValue) {
      if (imMsgBodyListBuilder_ == null) {
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.add(index, builderForValue.build());
        onChanged();
      } else {
        imMsgBodyListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder addAllImMsgBodyList(
        java.lang.Iterable<? extends com.ww.mall.proto.im.ImMsgBodyRequest> values) {
      if (imMsgBodyListBuilder_ == null) {
        ensureImMsgBodyListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, imMsgBodyList_);
        onChanged();
      } else {
        imMsgBodyListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder clearImMsgBodyList() {
      if (imMsgBodyListBuilder_ == null) {
        imMsgBodyList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        imMsgBodyListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public Builder removeImMsgBodyList(int index) {
      if (imMsgBodyListBuilder_ == null) {
        ensureImMsgBodyListIsMutable();
        imMsgBodyList_.remove(index);
        onChanged();
      } else {
        imMsgBodyListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public com.ww.mall.proto.im.ImMsgBodyRequest.Builder getImMsgBodyListBuilder(
        int index) {
      return getImMsgBodyListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder getImMsgBodyListOrBuilder(
        int index) {
      if (imMsgBodyListBuilder_ == null) {
        return imMsgBodyList_.get(index);  } else {
        return imMsgBodyListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public java.util.List<? extends com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder> 
         getImMsgBodyListOrBuilderList() {
      if (imMsgBodyListBuilder_ != null) {
        return imMsgBodyListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(imMsgBodyList_);
      }
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public com.ww.mall.proto.im.ImMsgBodyRequest.Builder addImMsgBodyListBuilder() {
      return getImMsgBodyListFieldBuilder().addBuilder(
          com.ww.mall.proto.im.ImMsgBodyRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public com.ww.mall.proto.im.ImMsgBodyRequest.Builder addImMsgBodyListBuilder(
        int index) {
      return getImMsgBodyListFieldBuilder().addBuilder(
          index, com.ww.mall.proto.im.ImMsgBodyRequest.getDefaultInstance());
    }
    /**
     * <code>repeated .ImMsgBodyRequest imMsgBodyList = 1;</code>
     */
    public java.util.List<com.ww.mall.proto.im.ImMsgBodyRequest.Builder> 
         getImMsgBodyListBuilderList() {
      return getImMsgBodyListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ww.mall.proto.im.ImMsgBodyRequest, com.ww.mall.proto.im.ImMsgBodyRequest.Builder, com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder> 
        getImMsgBodyListFieldBuilder() {
      if (imMsgBodyListBuilder_ == null) {
        imMsgBodyListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ww.mall.proto.im.ImMsgBodyRequest, com.ww.mall.proto.im.ImMsgBodyRequest.Builder, com.ww.mall.proto.im.ImMsgBodyRequestOrBuilder>(
                imMsgBodyList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        imMsgBodyList_ = null;
      }
      return imMsgBodyListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ImMsgBodyListRequest)
  }

  // @@protoc_insertion_point(class_scope:ImMsgBodyListRequest)
  private static final com.ww.mall.proto.im.ImMsgBodyListRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ww.mall.proto.im.ImMsgBodyListRequest();
  }

  public static com.ww.mall.proto.im.ImMsgBodyListRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ImMsgBodyListRequest>
      PARSER = new com.google.protobuf.AbstractParser<ImMsgBodyListRequest>() {
    @java.lang.Override
    public ImMsgBodyListRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ImMsgBodyListRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ImMsgBodyListRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ww.mall.proto.im.ImMsgBodyListRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

