server:
  port: 8080

app:
  servers:
    TEST-1:
      mall-basic-portal:
        host: "192.168.10.143"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        # privateKeyPath: "/home/dev/.ssh/id_rsa"
        # privateKeyPassphrase: ""
        # preferredAuthentications: "publickey,password,keyboard-interactive"
        # connectTimeoutMs: 8000
        logPath: "/data/B2B2C/mall-basic-portal/target/logs"
      mall-basic-service:
        host: "192.168.10.143"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-basic-service/target/logs"
      mall-auth-service:
        host: "192.168.10.143"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-auth-service/target/logs"
      mall-ext-service:
        host: "192.168.10.143"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-ext-service/target/logs"

    TEST-2:
      mall-basic-portal:
        host: "192.168.10.185"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-basic-portal/target/logs"
      mall-basic-service:
        host: "192.168.10.185"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-basic-service/target/logs"
      mall-auth-service:
        host: "192.168.10.185"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-auth-service/target/logs"
      mall-ext-service:
        host: "192.168.10.185"
        port: 22
        username: "root"
        password: "2020pflm@143#"
        logPath: "/data/B2B2C/mall-ext-service/target/logs"
