// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/imServer.proto

// Protobuf Java Version: 3.25.1
package com.ww.app.proto.im.core;

public final class ImMsgBizProto {
  private ImMsgBizProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021im/imServer.proto\032\013im/im.proto2\200\001\n\017ImS" +
      "erverService\0221\n\007sendMsg\022\021.ImMsgBodyReque" +
      "st\032\021.ImCommonResponse\"\000\022:\n\014batchSendMsg\022" +
      "\025.ImMsgBodyListRequest\032\021.ImCommonRespons" +
      "e\"\000B,\n\031com.ww.mall.proto.im.coreB\rImMsgB" +
      "izProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ww.app.proto.im.ImProto.getDescriptor(),
        });
    com.ww.app.proto.im.ImProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
